"""Unit tests for SageAdapter in mcp-geo-server."""
import pytest
from unittest.mock import patch
from mcp_geo_server.adapter import SageAdapter, SageEngineError

SAMPLE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<title>SAGE MCP Adapter Test Page</title>
<meta name="description" content="A valid test page for testing SAGE adapter integration with MCP server.">
<link rel="canonical" href="https://example.com/">
<script type="application/ld+json">
{"@context": "https://schema.org", "@type": "Organization", "name": "Adapter Corp", "url": "https://example.com"}
</script>
</head>
<body>
<h1>SAGE MCP Adapter Test Heading</h1>
<p>Cloud architecture is the structural foundation of modern digital products. It organizes data pipelines, distributed state machines, and failover automation across multiple geographic regions.</p>
<h2>What is Retrieval Augmented Generation?</h2>
<p>Retrieval Augmented Generation is a technique that supplies generative language models with external factual passages from a searchable knowledge base at inference time.</p>
</body>
</html>
"""


def test_adapter_audit_full():
    adapter = SageAdapter(default_backend="hashing")
    result = adapter.audit_full(html_content=SAMPLE_HTML, url="https://example.com")
    
    assert result["status"] == "success"
    assert result["tool"] == "audit_full"
    assert result["engine"]["name"] == "sage"
    assert result["engine"]["version"] == "1.0.0"
    assert result["server_version"] == "0.2.0"
    assert 0 <= result["score"] <= 100
    assert result["grade"] in ("A+", "A", "B", "C", "D", "F")
    assert len(result["findings"]) >= 20
    assert "llms.txt" in result["artifacts"]


def test_adapter_technical_seo():
    adapter = SageAdapter(default_backend="hashing")
    result = adapter.technical_seo(html_content=SAMPLE_HTML, url="https://example.com")
    
    assert result["status"] == "success"
    assert result["tool"] == "technical_seo"
    assert 0 <= result["score"] <= 100
    findings = result["findings"]
    assert any(f["check_id"] == "seo.title" for f in findings)
    assert any(f["check_id"] == "seo.canonical" for f in findings)


def test_adapter_aeo_readiness():
    adapter = SageAdapter(default_backend="hashing")
    result = adapter.aeo_readiness(html_content=SAMPLE_HTML, url="https://example.com")
    
    assert result["status"] == "success"
    assert result["tool"] == "aeo_readiness"
    findings = result["findings"]
    assert any(f["check_id"] == "aeo.jsonld_presence" for f in findings)
    assert any(f["check_id"] == "aeo.direct_answer_density" for f in findings)


def test_adapter_geo_readiness():
    adapter = SageAdapter(default_backend="hashing")
    result = adapter.geo_readiness(html_content=SAMPLE_HTML, url="https://example.com", backend="hashing")
    
    assert result["status"] == "success"
    assert result["tool"] == "geo_readiness"
    findings = result["findings"]
    assert any(f["check_id"] == "geo.citation_survival" for f in findings)
    assert result["metrics"]["chunk_count"] >= 1
    assert "citation_survival_proxy" in result["metrics"]


def test_adapter_entity_analysis():
    adapter = SageAdapter(default_backend="hashing")
    result = adapter.entity_analysis(html_content=SAMPLE_HTML, url="https://example.com")
    
    assert result["status"] == "success"
    assert result["tool"] == "entity_analysis"
    assert result["metrics"]["json_ld_blocks"] == 1
    assert "Organization" in result["metrics"]["entity_types"]


def test_adapter_citation_readiness():
    adapter = SageAdapter(default_backend="hashing")
    result = adapter.citation_readiness(html_content=SAMPLE_HTML, url="https://example.com", backend="hashing")
    
    assert result["status"] == "success"
    assert result["tool"] == "citation_readiness"
    assert "citation_survival_proxy" in result["metrics"]
    assert "csp_details" in result["metrics"]
    assert result["metrics"]["csp_details"]["metric_type"] == "heuristic_proxy"
    assert result["metrics"]["csp_details"]["calibrated_probability"] is False


def test_adapter_generate_llms_txt():
    adapter = SageAdapter(default_backend="hashing")
    llms = adapter.generate_llms_txt(html_content=SAMPLE_HTML, url="https://example.com", backend="hashing")
    assert llms.startswith("# ")
    assert "Generated by sage-audit" in llms


def test_adapter_evidence_metadata_preserved():
    adapter = SageAdapter(default_backend="hashing")
    result = adapter.geo_readiness(html_content=SAMPLE_HTML, url="https://example.com", backend="hashing")
    
    csp_finding = next(f for f in result["findings"] if f["check_id"] == "geo.citation_survival")
    assert csp_finding["evidence"] is not None
    assert csp_finding["evidence"]["level"] == "E5"
    assert csp_finding["evidence"]["evidence_type"] == "experimental_hypothesis"
    assert csp_finding["evidence"]["ranking_factor_claim"] is False


def test_adapter_error_handling_no_fallback():
    adapter = SageAdapter()
    
    # Missing both url and html_content raises ValueError
    with pytest.raises(ValueError):
        adapter.audit_full()

    # Engine error raises SageEngineError without fabricating scores
    with patch("sage_audit.SageAuditor.audit_html", side_effect=RuntimeError("Simulated engine crash")):
        with pytest.raises(SageEngineError) as excinfo:
            adapter.audit_full(html_content="<p>crash</p>")
        assert "SAGE Core execution error" in str(excinfo.value)
